# Generated by Django 4.0.1 on 2022-02-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_usuariojuego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(help_text='Texto', max_length=255, verbose_name='Pregunta'),
        ),
    ]
