# Generated by Django 4.0.1 on 2022-02-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(editable=False, max_length=255, verbose_name='Pregunta')),
                ('respuestas', models.JSONField(verbose_name='Respuestas')),
                ('respuesta_correcta', models.IntegerField(help_text='Respuesta correcta', verbose_name='Respuesta correcta')),
            ],
        ),
    ]
