# Generated by Django 4.0.1 on 2022-02-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregunta', models.TextField(editable=False, max_length=100, verbose_name='Pregunta')),
                ('Respuestas', models.JSONField(verbose_name='Respuestas')),
                ('Respuesta correcta', models.IntegerField(help_text='Respuesta correcta', verbose_name='Respuesta correcta')),
            ],
        ),
    ]
