# Generated by Django 4.0.1 on 2022-02-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='Pregunta',
            field=models.TextField(editable=False, max_length=255, verbose_name='Pregunta'),
        ),
    ]
