# Generated by Django 4.0.1 on 2022-02-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_alter_pregunta_pregunta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='Respuesta correcta',
            new_name='respuesta_correcta',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='Respuestas',
            new_name='respuestas',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='Pregunta',
            new_name='texto',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
